In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data/phase_2_data/processed/phase_2_partial_complete.csv')

In [21]:
df
def generate_binary_datasets(df, label):
    for idx, row in df.iterrows():
        if row.gold == label:
            df.at[idx, 'binary_label'] = int(1)
        else:
            df.at[idx, 'binary_label'] = int(0)
    
    return df

In [22]:
for label in df.gold.unique():
    bin_d = generate_binary_datasets(df, label)
    bin_d.to_csv(f'/Users/rt853/repos/UoB/bath-persuasion-detection/data/phase_2_data/processed/binary_datasets/{label}_binary_ds.csv', index=False)

In [23]:
bin_d

,text,gold,label,binary_label
0,"Hello gorgeous ,I’m *name* from call the midwi...",1-RAPPORT,0.0,0
1,Hi *name*. Where are you from?,8-NO-PERSUASION,0.0,0
2,I live in *location,1-RAPPORT,0.0,0
3,"I'm presently at *location*, Working with the ...",1-RAPPORT,0.0,0
4,You ?,1-RAPPORT,0.0,0
...,...,...,...,...
856,Yes,8-NO-PERSUASION,0.0,0
857,I thought it wouldnt work unless I accepted th...,8-NO-PERSUASION,0.0,0
858,No it would work babe,8-NO-PERSUASION,0.0,0
859,I will send you a message now,8-NO-PERSUASION,0.0,0
860,NaN,8-NO-PERSUASION,0.0,0